// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $device_commands from "./routes/device/commands.ts";
import * as $device_index from "./routes/device/index.ts";
import * as $device_register from "./routes/device/register.ts";
import * as $icons_temperature_svg from "./routes/icons/temperature.svg.ts";
import * as $index from "./routes/index.tsx";
import * as $oauth2_callback from "./routes/oauth2/callback.ts";
import * as $register from "./routes/register.ts";
import * as $trigger_name_ from "./routes/trigger/[name].ts";
import * as $GridButton from "./islands/GridButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
    routes: {
        "./routes/_app.tsx": $_app,
        "./routes/_middleware.ts": $_middleware,
        "./routes/device/commands.ts": $device_commands,
        "./routes/device/index.ts": $device_index,
        "./routes/device/register.ts": $device_register,
        "./routes/icons/temperature.svg.ts": $icons_temperature_svg,
        "./routes/index.tsx": $index,
        "./routes/oauth2/callback.ts": $oauth2_callback,
        "./routes/register.ts": $register,
        "./routes/trigger/[name].ts": $trigger_name_,
    },
    islands: {
        "./islands/GridButton.tsx": $GridButton,
    },
    baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
